version: '3.8'

services:
  python-container:
    image: malvinapap/app
    container_name: python-container
    ports:
      - 5002:5000
    volumes:
      - ./:/app
    networks:
      - mysql-network
  
  mysql-container:
    image: mysql:8.0.28
    container_name: mysql-container
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Abc@123456789
    volumes:
      - mysql-volume:/var/lib/mysql
      - mysql-volume-config:/etc/mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    name: mysql-network
volumes:
  mysql-volume:
  mysql-volume-config:
